sudo: false

language: python

python:
  - 3.6
  - 3.7

cache: pip

os:
  - linux

install:
  - pip install -e .
  - pip install -r requirements/base.txt
  - pip install tox
  - pip install coverage
  - pip install coveralls

script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then tox -e py36,coverage; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then tox -e py37,coverage,mypy,isort,pylint,flake8; fi

after_success:
  - coverage run --rcfile=.coveragerc -m unittest discover -s src
  - coveralls

notifications:
  email: false
